### ISSUE TITLE
Minor issues on hathor-wallet

### ISSUE THREAD

**Issue by thr0wn** [HathorNetwork/hathor-wallet#155]
Done:
- [x] Add thousand separator on value input when sending tokens #77 (PR: #152)
- [x] Wallet initial size can cut off some elements #90 (PR: #151)
- [x] (PR: chore: use wait-on concurrently with electron #153)
- [x] Improve words backup validation UX #150 (PR: #156)
- [x] Add loading on administrative tools actions #107 (Closed)

Doing:
~~Implement new version notification according to the design #113~~ (Not included)

To Do:

Owner: @thr0wn
